#ifndef MP_DEVICE_TYPE_H
#define MP_DEVICE_TYPE_H

enum Device_Type
{
    DEVICE_TYPE_BEGIN,
    DEVICE_TYPE_REAL_TERMINAL,
    DEVICE_TYPE_MULTIDEV_TERMINAL,//zfl
    DEVICE_TYPE_VIRTUAL_TERMINAL,
    DEVICE_TYPE_MP_VIDEO_ENCODE,
    DEVICE_TYPE_MP_VIDEO_DECODE,
    DEVICE_TYPE_MP_AMIX,
    DEVICE_TYPE_END
};

#endif // MP_DEVICE_TYPE_H
