#ifndef AUDIO_STREAM_TYPE_H
#define AUDIO_STREAM_TYPE_H

enum Audio_Encode_Type
{
    AUDIO_ENCODE_BEGIN,
    AUDIO_ENCODE_TYPE_ULAW,
    AUDIO_ENCODE_TYPE_ALAW,
    AUDIO_ENCODE_END
};

#endif // AUDIO_STREAM_TYPE_H
